PYTHONCXXFLAGS := $(filter-out -Wstrict-prototypes, $(shell python3.3-config --cflags)) 
PYTHONLDFLAGS := $(shell python3.3-config --ldflags)

GSTREAMERCXXFLAGS := $(filter-out -Wstring-prototypes, $(shell pkg-config --cflags gstreamer-{,plugins-base-}1.0))
GSTREAMERLDFLAGS := $(shell pkg-config --libs gstreamer-1.0)

BOOST_PYTHONCXXFLAGS := -I /Users/allie/boost
BOOST_PYTHONLDFLAGS := -L/Users/allie/boost/stage/lib

CXXFLAGS := -std=c++11 -stdlib=libstdc++ -fPIC

CXXFLAGS += $(GSTREAMERCXXFLAGS) $(PYTHONCXXFLAGS)
LDFLAGS += $(GSTREAMERLDFLAGS) $(PYTHONLDFLAGS)

default: python_library

SOFLAGS = -single_module -dynamiclib -install_name "$@" -lboost_python 

SUFFIX = dylib 

SNAMES = hello_gstreamer
SOBJ = $(addsuffix .$(SUFFIX), $(SNAMES))
ONAMES = player
OBJ = $(addsuffix .o, $(ONAMES))
SRCS = $(addsuffix .cpp, $(SNAMES) $(ONAMES))

python_library: $(SOBJ) $(OBJ) 

test: $(OBJ) main.o 
	$(CXX) -o test $(OBJ) main.o $(GSTREAMERLDFLAGS)

%.$(SUFFIX) : %.o $(OBJ)
	$(CXX)  $(LDFLAGS) $(BOOST_PYTHONLDFLAGS) $^ -o $(basename $@).so $(SOFLAGS)

.PHONY: clean
clean:
	rm -rf $(SOBJ) $(OBJ) main.o test

player.o: player.h
