# vim: set syntax=python
import os
boostincl=os.environ["BOOSTINCL"]
boostlibs=os.environ["BOOSTLIBS"]

env=Environment()
env["CXXFLAGS"]="--std=c++11"
env["CXX"]="clang++"

env.ParseConfig("pkg-config gstreamer-1.0 gstreamer-plugins-base-1.0 --cflags --libs")

env_py=env.Clone()
env_py.ParseConfig("python3.3-config --cflags --ldflags")
env_py.MergeFlags(env.ParseFlags("-fPIC -I"+boostincl+" -L"+boostlibs+" -lboost_python3"))

test=env.Program('test',['player.cpp','main.cpp'])

env["SHLIBPREFIX"]=""
env["SHLIBSUFFIX"]=".so"
hello_gstreamer_so=env_py.SharedLibrary('hello_gstreamer',['player.cpp','hello_gstreamer.cpp'])
