# This will define:
#   GSTREAMER_FOUND
#   GSTREAMER_INCLUDE_DIRS
#   GSTREAMER_LIBRARIES
#   GSTREAMER_DEFINITIONS
find_package(PkgConfig)
pkg_check_modules(PC_GSTREAMER gstreamer-1.0)
set(GSTREAMER_DEFINITIONS ${PC_GSTREAMER_CFLAGS_OTHER})

find_path(GSTREAMER_INCLUDE_DIR gst/gst.h
    HINTS ${PC_GSTREAMER_INCLUDEDIR} ${PC_GSTREAMER})
